[program:telegram_bot]
command=/root/.venv/bin/python -m modules.bot.simple_bot
directory=/app/backend
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/telegram_bot.err.log
stdout_logfile=/var/log/supervisor/telegram_bot.out.log
environment=PYTHONUNBUFFERED="1"
stopasgroup=true
killasgroup=true
